# feeder
feeder: feeders.feeder.Feeder
test_feeder_args:
  data_path: ./data/ipn/val_data_joint.npy
  label_path: ./data/ipn/val_label.pkl
  debug: False

# model
model: model.msg3d.Model
model_args:
  num_class: 13
  num_point: 21
  num_person: 1
  num_gcn_scales: 8
  num_g3d_scales: 8
  graph: graph.ipn.AdjMatrixGraph


# test
phase: test
device: 0
test_batch_size: 32
weights: ./pretrained_models/ipn_joint.pt

work_dir: ./eval/ipn/joint/
save_score: True