
work_dir: ./work_dir/ipn/msg3d_joint
model_saved_name: ./runs/train_joint
# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: ./data/ipn/train_data_joint.npy
  label_path: ./data/ipn/train_label.pkl
  debug: False

test_feeder_args:
  data_path: ./data/ipn/val_data_joint.npy
  label_path: ./data/ipn/val_label.pkl

# model
model: model.msg3d.Model
model_args:
  num_class: 13
  num_point: 21
  num_person: 1
  num_gcn_scales: 8
  num_g3d_scales: 8
  graph: graph.ipn.AdjMatrixGraph

# optim
# weight_decay: 0.0005
weight_decay: 0.0003
# base_lr: 0.05
base_lr: 0.05
step: [45, 55]

# training
num_epoch: 65
# device: [0, 1]
device: [0, 1, 2, 3]
# batch_size: 32
batch_size: 32
# forward_batch_size: 32
forward_batch_size: 16
# test_batch_size: 32
test_batch_size: 32
nesterov: True




