base_lr: 0.01
batch_size: 256
config: ./config/ipn/test_bone.yaml
device:
- 0
eval_interval: 5
feeder: feeders.feeder.Feeder
ignore_weights: []
log_interval: 100
model: model.agcn.Model
model_args:
  graph: graph.ipn.Graph
  graph_args:
    labeling_mode: spatial
  num_class: 13
  num_person: 1
  num_point: 21
model_saved_name: ./runs/ipn_agcn_bone
nesterov: false
num_epoch: 80
num_worker: 32
only_train_epoch: 0
only_train_part: false
optimizer: SGD
phase: test
print_log: true
save_interval: 2
save_score: true
seed: 1
show_topk:
- 1
- 5
start_epoch: 0
step:
- 20
- 40
- 60
test_batch_size: 16
test_feeder_args:
  data_path: ./data/ipn/val_data_bone.npy
  debug: false
  label_path: ./data/ipn/val_label.pkl
train_feeder_args: {}
warm_up_epoch: 0
weight_decay: 0.0005
weights: ./pre_train/ipn_agcn_bone.pt
work_dir: ./work_dir/ipn/ipn_agcn_bone
